import { Inter } from "next/font/google";
import SideDrawer from "./components/drawer/drawer";
import StoreProvider from "./StoreProvider";
import { SWRProvider } from "./SWRProvider";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <SWRProvider>
        <html lang="en">
          <body className={inter.className}>
            <SideDrawer />
            {children}
          </body>
        </html>
      </SWRProvider>
    </StoreProvider>
  );
}
